---
extends: ['@elastic/eslint-config-kibana', 'plugin:@elastic/eui/recommended']

settings:
  import/resolver:
    '@elastic/eslint-import-resolver-kibana':
      rootPackageName: 'anomaly-detection-dashboards'
