/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

import React from 'react';
import {
  EuiModal,
  EuiModalHeader,
  EuiModalHeaderTitle,
  EuiModalBody,
  EuiModalFooter,
  EuiButtonEmpty,
  EuiPanel,
  EuiText,
  EuiFlexGroup,
  EuiFlexItem,
  EuiLoadingSpinner,
  EuiSpacer,
  EuiBadge,
  EuiToolTip,
  EuiLink,
  EuiSmallButton,
} from '@elastic/eui';
import moment from 'moment';
import { CoreStart } from '../../../../../../src/core/public';
import { PLUGIN_NAME } from '../../../utils/constants';
import { formatEntityValue } from '../utils/insightCardHelpers';
import { buildDiscoverUrl } from '../utils/discoverLink';

export interface InsightCluster {
  indices: string[];
  detector_ids: string[];
  detector_names: string[];
  entities: string[];
  model_ids: string[];
  num_anomalies?: number;
  event_start: string;
  event_end: string;
  cluster_text: string;
  anomalies?: ClusterAnomaly[];
}

export interface ClusterAnomaly {
  model_id: string;
  detector_id: string;
  data_start_time: string;
  data_end_time: string;
}

interface EventDetailModalProps {
  cluster: InsightCluster;
  onClose: () => void;
  llmSummary?: string;
  llmLoading?: boolean;
  detectorDescriptions: Record<string, string>;
  detectorFeatures: Record<string, string[]>;
  detectorTimeFields: Record<string, string>;
  anomalyEntities: Record<string, string[]>;
  dataSourceId?: string;
  core: CoreStart | null;
}

const GENERIC_DESCRIPTION_PHRASES = ['generated by opensearch', 'auto-created', 'automatically created'];

export const EventDetailModal: React.FC<EventDetailModalProps> = ({
  cluster,
  onClose,
  llmSummary,
  llmLoading,
  detectorDescriptions,
  detectorFeatures,
  detectorTimeFields,
  anomalyEntities,
  dataSourceId,
  core,
}) => {
  const dsQuery = dataSourceId ? `?dataSourceId=${dataSourceId}` : '';

  const renderSummary = () => {
    if (llmSummary) {
      return (
        <EuiPanel color="primary" paddingSize="m" hasBorder={false} style={{ marginBottom: '16px' }}>
          <EuiText size="s">
            <strong>AI Summary</strong>
            <p>{llmSummary}</p>
          </EuiText>
        </EuiPanel>
      );
    }

    if (llmLoading) {
      return (
        <EuiPanel color="subdued" paddingSize="m" hasBorder={false} style={{ marginBottom: '16px' }}>
          <EuiFlexGroup alignItems="center" gutterSize="s">
            <EuiFlexItem grow={false}><EuiLoadingSpinner size="s" /></EuiFlexItem>
            <EuiFlexItem><EuiText size="s" color="subdued">Generating summary...</EuiText></EuiFlexItem>
          </EuiFlexGroup>
        </EuiPanel>
      );
    }

    // Fallback: structured summary + per-detector descriptions if available
    const detNames = cluster.detector_names?.join(', ') || '';
    const indices = cluster.indices?.join(', ') || '';
    const entityCount = cluster.entities?.length || 0;
    const anomalyCount = cluster.num_anomalies || cluster.anomalies?.length || 0;

    // Collect meaningful descriptions keyed by detector name
    const descEntries: { name: string; desc: string }[] = [];
    cluster.detector_ids.forEach((id, i) => {
      const d = detectorDescriptions[id];
      if (d && !GENERIC_DESCRIPTION_PHRASES.some(p => d.toLowerCase().includes(p))) {
        descEntries.push({ name: cluster.detector_names?.[i] || id, desc: d });
      }
    });

    return (
      <EuiText size="s" style={{ marginBottom: '12px' }}>
        <p>
          {anomalyCount} {anomalyCount === 1 ? 'anomaly' : 'anomalies'} detected
          {detNames && <> by <strong>{detNames}</strong></>}
          {indices && <> on <strong>{indices}</strong></>}
          {entityCount > 0 && <>, affecting {entityCount} {entityCount === 1 ? 'entity' : 'entities'}</>}
          .
        </p>
        {descEntries.map((entry, i) => (
          <p key={i}><strong>{entry.name}</strong>: {entry.desc}</p>
        ))}
      </EuiText>
    );
  };

  const renderAnomalies = () => {
    if (!cluster.anomalies?.length) return null;

    const grouped: Record<string, ClusterAnomaly[]> = {};
    cluster.anomalies.forEach((a) => {
      if (!grouped[a.detector_id]) grouped[a.detector_id] = [];
      grouped[a.detector_id].push(a);
    });

    return (
      <>
        <EuiSpacer size="m" />
        <EuiText><h3>Anomalies ({cluster.anomalies.length})</h3></EuiText>
        <EuiSpacer size="s" />
        {Object.entries(grouped).map(([detId, anomalies]) => {
          const detName = cluster.detector_names?.[cluster.detector_ids.indexOf(detId)] || detId;
          const features = detectorFeatures[detId];
          return (
            <EuiPanel key={detId} hasBorder paddingSize="m" style={{ marginBottom: '12px' }}>
              <EuiFlexGroup alignItems="center" gutterSize="s">
                <EuiFlexItem>
                  <EuiText size="s">
                    <strong>
                      <EuiLink href={`${PLUGIN_NAME}#/detectors/${detId}/results${dsQuery}`} target="_blank">
                        {detName}
                      </EuiLink>
                    </strong>
                  </EuiText>
                </EuiFlexItem>
                {features && features.length > 0 && (
                  <EuiFlexItem grow={false}>
                    <EuiText size="xs" color="subdued">{features.join(', ')}</EuiText>
                  </EuiFlexItem>
                )}
              </EuiFlexGroup>
              <EuiSpacer size="s" />
              {anomalies.map((anomaly, aIndex) => {
                const entityValues = anomalyEntities[anomaly.model_id];
                const entityLabel = entityValues
                  ? entityValues.map(formatEntityValue).join(', ')
                  : undefined;
                return (
                  <EuiFlexGroup key={aIndex} alignItems="center" gutterSize="m" style={{ marginBottom: '4px' }}>
                    <EuiFlexItem>
                      <EuiText size="s">
                        {entityLabel ? (
                          <EuiToolTip content={entityValues!.join(', ')}>
                            <span>{entityLabel}</span>
                          </EuiToolTip>
                        ) : (
                          <span style={{ color: '#98A2B3' }}>All data</span>
                        )}
                      </EuiText>
                    </EuiFlexItem>
                    <EuiFlexItem grow={false}>
                      <EuiText size="xs" color="subdued">
                        {moment(anomaly.data_start_time).format('lll')} → {moment(anomaly.data_end_time).format('lll')}
                      </EuiText>
                    </EuiFlexItem>
                    <EuiFlexItem grow={false}>
                      <EuiSmallButton
                        iconType="discoverApp"
                        size="s"
                        onClick={async () => {
                          if (!core) return;
                          const url = await buildDiscoverUrl(core, {
                            indices: cluster.indices,
                            startTime: anomaly.data_start_time,
                            endTime: anomaly.data_end_time,
                            entities: anomalyEntities[anomaly.model_id] || [],
                            timeField: detectorTimeFields[anomaly.detector_id],
                            dataSourceId,
                          });
                          if (url) window.open(url, '_blank');
                        }}
                      >
                        Discover
                      </EuiSmallButton>
                    </EuiFlexItem>
                  </EuiFlexGroup>
                );
              })}
            </EuiPanel>
          );
        })}
      </>
    );
  };

  return (
    <EuiModal onClose={onClose} style={{ minWidth: '700px' }}>
      <EuiModalHeader>
        <EuiModalHeaderTitle><h2>Event Details</h2></EuiModalHeaderTitle>
      </EuiModalHeader>
      <EuiModalBody>
        {renderSummary()}
        <EuiText size="s" color="subdued">
          {moment(cluster.event_start).format('lll')} → {moment(cluster.event_end).format('lll')} ({moment.duration(moment(cluster.event_end).diff(moment(cluster.event_start))).humanize()})
        </EuiText>
        {cluster.entities.length > 0 && (
          <>
            <EuiSpacer size="s" />
            <EuiText><h3>Affected Resources ({cluster.entities.length})</h3></EuiText>
            <EuiSpacer size="xs" />
            <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
              {cluster.entities.map((entity, index) => (
                <EuiToolTip key={index} content={entity}>
                  <EuiBadge color="hollow">{formatEntityValue(entity)}</EuiBadge>
                </EuiToolTip>
              ))}
            </div>
          </>
        )}
        <EuiSpacer size="m" />
        {renderAnomalies()}
      </EuiModalBody>
      <EuiModalFooter>
        <EuiButtonEmpty onClick={onClose}>Close</EuiButtonEmpty>
      </EuiModalFooter>
    </EuiModal>
  );
};
