name: Build and upload artifacts
on:
  push:
    tags:
      - v*

env:
  OPENSEARCH_DASHBOARDS_VERSION: 1.1.0
jobs:
  Build-and-upload:
    name: Build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}
          token: ${{ secrets.OPENSEARCH_DASHBOARDS_OSS_ACCESS }}
          path: opensearch-dashboards

      - name: Get node and yarn versions
        id: versions_step
        run: |
          echo "::set-output name=node_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.node).match(/[.0-9]+/)[0]")"
          echo "::set-output name=yarn_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.yarn).match(/[.0-9]+/)[0]")"

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions_step.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install correct yarn version for OpenSearch Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions_step.outputs.yarn_version }}

      - name: Checkout Anomaly Detection OpenSearch Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin

      - name: Bootstrap the plugin
        run: |
          cd OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
          yarn osd bootstrap

      - name: Build the artifact
        run: |
          cd OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
          yarn build

      - name: Upload to S3
        run: |
          cd OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
          zip=`ls build/*.zip`

          # Inject the build number before the suffix
          zip_outfile=`basename ${zip%.zip}-build-${GITHUB_RUN_NUMBER}.zip`

          s3_prefix="s3://staging.artifacts.opendistroforelasticsearch.amazon.com/snapshots/kibana-plugins/anomaly-detection/"

          echo "Copying ${zip} to ${s3_prefix}${zip_outfile}"
          aws s3 cp --quiet $zip ${s3_prefix}${zip_outfile}
