name: Unit tests workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  OPENSEARCH_DASHBOARDS_VERSION: '1.0'
jobs:
  tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}
          path: OpenSearch-Dashboards
      - name: Get node and yarn versions
        id: versions_step
        run: |
          echo "::set-output name=node_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.node).match(/[.0-9]+/)[0]")"
          echo "::set-output name=yarn_version::$(node -p "(require('./OpenSearch-Dashboards/package.json').engines.yarn).match(/[.0-9]+/)[0]")"
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.versions_step.outputs.node_version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install correct yarn version for OpenSearch Dashboards
        run: |
          npm uninstall -g yarn
          echo "Installing yarn ${{ steps.versions_step.outputs.yarn_version }}"
          npm i -g yarn@${{ steps.versions_step.outputs.yarn_version }}
      - name: Checkout Anomaly Detection OpenSearch Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
      - name: Bootstrap the plugin
        run: |
          cd OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
          yarn osd bootstrap
      - name: Run tests
        run: |
          cd OpenSearch-Dashboards/plugins/anomaly-detection-dashboards-plugin
          yarn run test:jest --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./OpenSearch-Dashboards/plugins/anomaly-detection-opensearch-dashboard-plugin/coverage/cobertura-coverage.xml
          flags: unittests
          name: ad-opensearch-dashboards-ut-codecov
